import type { RMClient } from '@/types/api'

// The RM's fixed book of 8 AU institutional clients.
//
// Company names are REAL; ALL financial data is SYNTHETIC and for demonstration only.
// This module is the authoritative source of every figure the UI renders (Constitution
// Principle I) and the static "yesterday's briefing" floor that guarantees the dashboard
// works with zero live LLM (Principle II). Each client carries a 3-item, urgency-ordered
// `nextBest`. APRA APS 210 (liquidity; warning zone at liquidityScore < 50) is the
// recurring regulatory reference.

const RM = 'Sarah Chen'
const RM_EMAIL = 'sarah.chen@aussiebank.com.au'

export const RM_CLIENTS: RMClient[] = [
  {
    id: 'c01',
    name: 'AustralianSuper',
    short: 'AUS',
    type: 'Superannuation Fund',
    tier: 'Strategic',
    rm: RM,
    rmEmail: RM_EMAIL,
    currency: 'AUD',
    currencySymbol: 'A$',
    netPosition: 2400,
    trend: 'up',
    exposure: 5200,
    revenue: 42,
    revenueYoY: 8.4,
    products: ['DEPOSIT', 'REPO', 'FX_SWAP', 'TERM_LOAN'],
    productValues: { DEPOSIT: 1800, REPO: 1800, FX_SWAP: 900, TERM_LOAN: 700 },
    currencies: { AUD: 85, USD: 12, GBP: 3 },
    liquidityScore: 72,
    scoreTrend: 'stable',
    lastContact: '2026-06-28',
    nextMeeting: '2026-07-14',
    alertLevel: 'medium',
    alertText:
      'A$1,800M REPO book matures in 14 days — rate-lock window open ahead of the expected RBA move.',
    cashFlows: [
      40, 55, -20, 60, 75, 30, -15, 50, 65, 45, -30, 70, 80, 35, -10, 55, 60, 40, -25, 65, 75, 50,
      20, -15, 60, 70, 45, 30, -20, 55,
    ],
    nextBest: [
      {
        urgency: 'high',
        action: 'Lock REPO rollover rate',
        text: 'The A$1,800M REPO book matures in 14 days. Locking the rollover rate now protects the buffer that keeps the liquidity score at 72, comfortably above the APRA APS 210 warning zone.',
        acts: ['Book rate call', 'Send term sheet'],
      },
      {
        urgency: 'medium',
        action: 'Extend deposit ladder',
        text: 'With A$1,800M in deposits and a A$2,400M net surplus, extending the deposit ladder locks in yield. Frame it against the A$5,200M total exposure.',
        acts: ['Model ladder'],
      },
      {
        urgency: 'low',
        action: 'Review FX hedge mix',
        text: 'USD sits at 12% of the book across A$900M of FX swaps. A light review confirms the hedge mix still fits the mandate.',
        acts: ['FX review'],
      },
    ],
  },
  {
    id: 'c02',
    name: 'Future Fund',
    short: 'FF',
    type: 'Sovereign Wealth Fund',
    tier: 'Strategic',
    rm: RM,
    rmEmail: RM_EMAIL,
    currency: 'AUD',
    currencySymbol: 'A$',
    netPosition: 6800,
    trend: 'up',
    exposure: 3100,
    revenue: 58,
    revenueYoY: 12.1,
    products: ['DEPOSIT', 'TERM_DEPOSIT', 'FX_FORWARD', 'BOND'],
    productValues: { DEPOSIT: 2600, TERM_DEPOSIT: 2200, FX_FORWARD: 1200, BOND: 1500 },
    currencies: { AUD: 60, USD: 28, EUR: 8, JPY: 4 },
    liquidityScore: 94,
    scoreTrend: 'improving',
    lastContact: '2026-07-01',
    nextMeeting: '2026-07-21',
    alertLevel: 'none',
    alertText:
      'Strong liquidity (score 94, well clear of APS 210). A$2,200M term deposits roll in Q3 — reinvestment opportunity.',
    cashFlows: [
      80, 90, 60, -20, 100, 110, 70, 50, -15, 95, 120, 85, 60, -10, 105, 115, 75, 55, -20, 100,
      110, 80, 65, 40, -15, 95, 105, 70, 60, 50,
    ],
    nextBest: [
      {
        urgency: 'high',
        action: 'Pitch term reinvestment',
        text: 'A$2,200M of term deposits roll in Q3 while the liquidity score sits at 94. Bring a reinvestment proposal that keeps duration aligned to the mandate.',
        acts: ['Prepare pitch', 'Book meeting'],
      },
      {
        urgency: 'medium',
        action: 'Propose duration extension',
        text: 'The A$1,500M bond allocation has room to extend duration given the A$6,800M net surplus. Model the trade-off before the July review.',
        acts: ['Model duration'],
      },
      {
        urgency: 'low',
        action: 'Review FX forward book',
        text: 'USD is 28% of the book across A$1,200M of forwards. Confirm the hedge ratio still matches the reserve policy.',
        acts: ['FX review'],
      },
    ],
  },
  {
    id: 'c03',
    name: 'Macquarie AM',
    short: 'MQG',
    type: 'Asset Manager',
    tier: 'Core',
    rm: RM,
    rmEmail: RM_EMAIL,
    currency: 'AUD',
    currencySymbol: 'A$',
    netPosition: -320,
    trend: 'down',
    exposure: 4100,
    revenue: 28,
    revenueYoY: -3.2,
    products: ['REPO', 'MARGIN_LOAN', 'FX_SWAP', 'RCF'],
    productValues: { REPO: 1600, MARGIN_LOAN: 1200, FX_SWAP: 800, RCF: 500 },
    currencies: { AUD: 70, USD: 25, HKD: 5 },
    liquidityScore: 42,
    scoreTrend: 'deteriorating',
    lastContact: '2026-06-25',
    nextMeeting: '2026-07-08',
    alertLevel: 'critical',
    alertText:
      'Liquidity score 42 — below the APRA APS 210 warning threshold of 50. RCF A$500M drawn; net position negative at -A$320M.',
    cashFlows: [
      -40, 20, -55, -30, 15, -60, -45, 10, -70, -50, 25, -40, -65, -35, -55, -25, -70, -45, -60,
      -30, -50, -75, -40, -55, -35, -65, -45, -70, -50, -60,
    ],
    nextBest: [
      {
        urgency: 'critical',
        action: 'Address APS 210 breach',
        text: 'The liquidity score has fallen to 42, below the APRA APS 210 warning threshold of 50, with the A$500M RCF drawn and net position at -A$320M. Escalate and agree a remediation path this week.',
        acts: ['Escalate', 'Book urgent call'],
      },
      {
        urgency: 'high',
        action: 'Restructure REPO funding',
        text: 'The A$1,600M REPO book is the largest funding line. Restructuring tenor would relieve the pressure dragging the liquidity score below APS 210.',
        acts: ['Model restructure'],
      },
      {
        urgency: 'medium',
        action: 'Review margin exposure',
        text: 'A$1,200M of margin lending adds to the A$4,100M total exposure. A risk review checks the buffer against further drawdown.',
        acts: ['Risk review'],
      },
    ],
  },
  {
    id: 'c04',
    name: 'QIC',
    short: 'QIC',
    type: 'State Gov Investment',
    tier: 'Core',
    rm: RM,
    rmEmail: RM_EMAIL,
    currency: 'AUD',
    currencySymbol: 'A$',
    netPosition: 1450,
    trend: 'stable',
    exposure: 2800,
    revenue: 22,
    revenueYoY: 4.0,
    products: ['DEPOSIT', 'FX_FORWARD', 'FX_SWAP', 'BOND'],
    productValues: { DEPOSIT: 1100, FX_FORWARD: 900, FX_SWAP: 600, BOND: 700 },
    currencies: { AUD: 52, USD: 38, EUR: 10 },
    liquidityScore: 68,
    scoreTrend: 'stable',
    lastContact: '2026-06-30',
    nextMeeting: '2026-07-16',
    alertLevel: 'high',
    alertText:
      'USD concentration at 38% of the book — above the 30% internal limit. A$1,500M of FX exposure to review.',
    cashFlows: [
      30, -25, 40, 20, -35, 50, 25, -20, 45, 35, -30, 55, 30, -15, 40, 25, -40, 50, 35, -25, 45, 30,
      20, -35, 55, 40, -20, 35, 25, -30,
    ],
    nextBest: [
      {
        urgency: 'high',
        action: 'Reduce USD concentration',
        text: 'USD is 38% of the book, above the 30% internal limit, spread across A$900M of forwards and A$600M of swaps. Propose a rebalance ahead of the next mandate review.',
        acts: ['Propose hedge', 'Model rebalance'],
      },
      {
        urgency: 'medium',
        action: 'Ladder AUD deposits',
        text: 'A$1,100M of AUD deposits can be laddered to lock yield without adding FX risk to the A$2,800M book.',
        acts: ['Model ladder'],
      },
      {
        urgency: 'low',
        action: 'Review bond duration',
        text: 'The A$700M bond sleeve has a stable liquidity score of 68 behind it. Confirm duration still matches the state investment horizon.',
        acts: ['Duration review'],
      },
    ],
  },
  {
    id: 'c05',
    name: 'Aware Super',
    short: 'AWR',
    type: 'Superannuation Fund',
    tier: 'Core',
    rm: RM,
    rmEmail: RM_EMAIL,
    currency: 'AUD',
    currencySymbol: 'A$',
    netPosition: 1900,
    trend: 'down',
    exposure: 3400,
    revenue: 26,
    revenueYoY: 2.5,
    products: ['DEPOSIT', 'REPO', 'TERM_DEPOSIT', 'FX_SWAP'],
    productValues: { DEPOSIT: 1400, REPO: 900, TERM_DEPOSIT: 800, FX_SWAP: 500 },
    currencies: { AUD: 80, USD: 15, GBP: 5 },
    liquidityScore: 58,
    scoreTrend: 'deteriorating',
    lastContact: '2026-06-27',
    nextMeeting: '2026-07-11',
    alertLevel: 'high',
    alertText:
      'LCR trending toward 110% — approaching the APRA APS 210 warning band. Liquidity score 58 and deteriorating.',
    cashFlows: [
      20, -30, 15, -45, 25, -35, 10, -50, 20, -40, 15, -55, 25, -45, 10, -35, 20, -50, 15, -40, 25,
      -30, -45, 10, -55, 20, -40, 15, -35, -50,
    ],
    nextBest: [
      {
        urgency: 'high',
        action: 'Shore up LCR buffer',
        text: 'The LCR is trending toward 110% and the liquidity score has slipped to 58 and is deteriorating. Model a buffer top-up before it enters the APRA APS 210 warning band.',
        acts: ['Model buffer', 'Book review'],
      },
      {
        urgency: 'medium',
        action: 'Extend REPO tenor',
        text: 'Extending the A$900M REPO tenor would steady the funding profile and support the LCR against the A$3,400M exposure.',
        acts: ['Model tenor'],
      },
      {
        urgency: 'low',
        action: 'Confirm deposit mix',
        text: 'A$1,400M of deposits anchor the book at 80% AUD. Confirm the mix still fits the member-liquidity profile.',
        acts: ['Log review'],
      },
    ],
  },
  {
    id: 'c06',
    name: 'Qantas Airways',
    short: 'QAN',
    type: 'Airline / Transport',
    tier: 'Core',
    rm: RM,
    rmEmail: RM_EMAIL,
    currency: 'AUD',
    currencySymbol: 'A$',
    netPosition: -180,
    trend: 'down',
    exposure: 2600,
    revenue: 19,
    revenueYoY: -1.8,
    products: ['RCF', 'FX_FORWARD', 'COMMODITY_SWAP', 'TERM_LOAN'],
    productValues: { RCF: 700, FX_FORWARD: 600, COMMODITY_SWAP: 800, TERM_LOAN: 500 },
    currencies: { AUD: 65, USD: 32, EUR: 3 },
    liquidityScore: 61,
    scoreTrend: 'deteriorating',
    lastContact: '2026-06-29',
    nextMeeting: '2026-07-13',
    alertLevel: 'high',
    alertText:
      'Fuel hedge coverage at 64% — below the 70% policy floor. Oil-price exposure rising on the A$800M commodity book.',
    cashFlows: [
      -15, 25, -40, 10, -30, 20, -45, 15, -25, -50, 20, -35, 10, -40, 25, -30, -55, 15, -45, 20,
      -35, 10, -50, 25, -40, 15, -30, -45, 20, -35,
    ],
    nextBest: [
      {
        urgency: 'high',
        action: 'Increase fuel hedge cover',
        text: 'Fuel hedge coverage sits at 64%, below the 70% policy floor, against an A$800M commodity swap book that is increasingly oil-price sensitive. Propose topping up cover before the next fuel cycle.',
        acts: ['Propose hedge', 'Book desk call'],
      },
      {
        urgency: 'medium',
        action: 'Review RCF headroom',
        text: 'With net position at -A$180M, confirm headroom on the A$700M RCF so seasonal cash swings stay funded.',
        acts: ['Check headroom'],
      },
      {
        urgency: 'low',
        action: 'Hedge USD payables',
        text: 'USD is 32% of the book across A$600M of forwards. A light review keeps aircraft-lease payables covered.',
        acts: ['FX review'],
      },
    ],
  },
  {
    id: 'c07',
    name: 'Woodside Energy',
    short: 'WDS',
    type: 'Oil & Gas Producer',
    tier: 'Strategic',
    rm: RM,
    rmEmail: RM_EMAIL,
    currency: 'AUD',
    currencySymbol: 'A$',
    netPosition: 3200,
    trend: 'up',
    exposure: 3900,
    revenue: 38,
    revenueYoY: 9.5,
    products: ['DEPOSIT', 'COMMODITY_SWAP', 'FX_FORWARD', 'BOND'],
    productValues: { DEPOSIT: 1900, COMMODITY_SWAP: 1000, FX_FORWARD: 700, BOND: 900 },
    currencies: { AUD: 58, USD: 40, EUR: 2 },
    liquidityScore: 80,
    scoreTrend: 'improving',
    lastContact: '2026-07-02',
    nextMeeting: '2026-07-18',
    alertLevel: 'medium',
    alertText:
      'A$1,000M commodity hedge rolls in 21 days. Surplus liquidity (score 80) — deployment options open.',
    cashFlows: [
      60, 75, 45, -20, 85, 95, 55, 40, -15, 80, 100, 65, 50, -10, 90, 105, 70, 45, -25, 85, 95, 60,
      50, 30, -15, 80, 90, 55, 45, 40,
    ],
    nextBest: [
      {
        urgency: 'high',
        action: 'Roll commodity hedge',
        text: 'The A$1,000M commodity hedge rolls in 21 days while the liquidity score sits at a healthy 80. Book the roll early to secure pricing on the production profile.',
        acts: ['Book roll', 'Send term sheet'],
      },
      {
        urgency: 'medium',
        action: 'Deploy surplus liquidity',
        text: 'With a A$3,200M net surplus and A$1,900M in deposits, there is scope to deploy into term or short-duration instruments. Model options for the July review.',
        acts: ['Model deployment'],
      },
      {
        urgency: 'low',
        action: 'Hedge USD revenue',
        text: 'USD is 40% of the book across A$700M of forwards, tracking export receipts. Confirm the hedge ratio still fits guidance.',
        acts: ['FX review'],
      },
    ],
  },
  {
    id: 'c08',
    name: 'Ampol Limited',
    short: 'ALD',
    type: 'Fuel Refiner / Retailer',
    tier: 'Core',
    rm: RM,
    rmEmail: RM_EMAIL,
    currency: 'AUD',
    currencySymbol: 'A$',
    netPosition: -540,
    trend: 'down',
    exposure: 3300,
    revenue: 21,
    revenueYoY: -6.4,
    products: ['RCF', 'COMMODITY_SWAP', 'FX_FORWARD', 'TERM_LOAN'],
    productValues: { RCF: 900, COMMODITY_SWAP: 1100, FX_FORWARD: 600, TERM_LOAN: 700 },
    currencies: { AUD: 60, USD: 38, SGD: 2 },
    liquidityScore: 46,
    scoreTrend: 'deteriorating',
    lastContact: '2026-06-24',
    nextMeeting: '2026-07-07',
    alertLevel: 'critical',
    alertText:
      'Crack-spread collapse: RCF A$900M drawn of a A$1,000M facility. Liquidity score 46 — below the APS 210 threshold. Net position -A$540M.',
    cashFlows: [
      -55, 15, -70, -40, 10, -65, -50, 20, -80, -45, -60, -35, -75, -50, -65, -30, -70, -55, -60,
      -40, -50, -85, -45, -60, -35, -75, -50, -70, -55, -65,
    ],
    nextBest: [
      {
        urgency: 'critical',
        action: 'Manage RCF drawdown',
        text: 'The crack-spread collapse has driven the RCF to A$900M drawn of a A$1,000M facility, with the liquidity score at 46 — below the APRA APS 210 threshold of 50 — and net position at -A$540M. Escalate and agree a funding bridge immediately.',
        acts: ['Escalate', 'Book urgent call'],
      },
      {
        urgency: 'high',
        action: 'Hedge crack-spread exposure',
        text: 'The A$1,100M commodity swap book is the main lever on refining margin. Restructuring cover would stem the cash drain pulling the score below APS 210.',
        acts: ['Propose hedge'],
      },
      {
        urgency: 'medium',
        action: 'Review USD payables',
        text: 'USD is 38% of the book across A$600M of forwards, tracking crude purchases. Confirm cover holds through the drawdown.',
        acts: ['FX review'],
      },
    ],
  },
]
